apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-rs
spec:
  selector:
    matchLabels:
      app: mongo-rs
  serviceName: mongo-rs
  replicas: 3
  template:
    metadata:
      labels:
        app: mongo-rs
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo-rs
        image: mongo
        command: 
        - mongod 
        - --bind_ip_all
        - --replSet
        - rs0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-rs
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-rs
    spec:
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 1Gi 
